version: "3"
services:
  cuquibot:
    container_name: "cuquibot"
    image: cuquibot:latest
    volumes:
      - ~/docker/imagenes/bots/cuquibot/src/secretos:/app/secretos
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
